### ISSUE TITLE
typo？

### ISSUE THREAD

**Issue by pumpkinpbk** [zion-group/VerilogCodingStyle#1]
assign dat  = {$bits(a){(x==2'd1 && y==2'd1)}} & a;
              {$bits(b){(x==2'd1 && y==2'd1)}} & b;
              {$bits(c){(x==2'd1 && y==2'd1)}} & c;
              {$bits(d){(x==2'd1 && y==2'd1)}} & d;
这里是不是写错了，应该是
assign dat  = {$bits(a){(x==2'd1 && y==2'd1)}} & a |
                      {$bits(b){(x==2'd2 && y==2'd2)}} & b |
                      {$bits(c){(x==2'd3 && y==2'd3)}} & c |
                      {$bits(d){(x==2'd0 && y==2'd0)}} & d;

**Comment by WenhMa** [comment]
多谢反馈,已经修正这个bug了.
